const name = "Denis";
const birthCity = "Cariacica";
let birthYear = 2001;
console.log (name);
console.log (birthCity);
console.log (birthYear);
birthYear = 2000;
console.log (birthYear);
birthCity = "Vitória";
console.log (birthCity);